version: '3.8'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx.Dockerfile
        depends_on:
            - php
            - mysql
        container_name: laravel11_nginx
        ports:
            - "${NGINX_PORT:-8100}:80"
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel-network
        restart: unless-stopped
        env_file:
            - docker.env

    php:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: laravel11_php
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel-network
        restart: unless-stopped
        env_file:
            - docker.env

    mysql:
        image: mysql:8.1
        platform: linux/amd64
        container_name: laravel11_mysql
        ports:
            - "${MYSQL_PORT:-3306}:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laraveldb}
            MYSQL_USER: ${MYSQL_USER:-laravel}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
        networks:
            - laravel-network
        restart: unless-stopped
        env_file:
            - docker.env

    composer:
        image: composer:latest
        container_name: laravel11_composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel-network
        env_file:
            - docker.env

    artisan:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: laravel11_artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel-network
        env_file:
            - docker.env

    npm:
        image: node:${NODE_VERSION:-current-alpine}
        container_name: laravel11_npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel-network
        env_file:
            - docker.env

    phpmyadmin:
        image: arm64v8/phpmyadmin:5.2.0
        container_name: laravel11_phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT:-8080}:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
        depends_on:
            - mysql
        networks:
            - laravel-network
        restart: unless-stopped
        env_file:
            - docker.env

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql_data:





